# https://probot.github.io/apps/settings/
labels:
  - name: 'bug ğŸ'
    color: '#FC2929'
  - name: 'dependency'
    color: '#'
  - name: duplicate ğŸ‘¯
    color: '#EDEDED'
  - name: enhancement ğŸ™ğŸ»
    color: '#1D76DB'
    oldname: feature-request ğŸ™ğŸ»
  - name: github-sponsor â¤ï¸
    color: '#815543'
  - name: needs-more-info ğŸ•µğŸ¼
    color: '#f3ffa8'
  - name: wont-fix ğŸ™…ğŸ¼
    color: '#EDEDED'
