# https://probot.github.io/apps/settings/
labels:
  - name: 'bug ğŸ'
    color: '#FC2929'
  - name: duplicate ğŸ‘¯
    color: '#FBCA04'
  - name: feature-request ğŸ™ğŸ»
    color: '#FBCA04'
  - name: github-sponsor â¤ï¸
    color: '#815543'
  - name: needs-more-info ğŸ•µğŸ¼
    color: '#f3ffa8'
  - name: wont-fix ğŸ™…ğŸ¼
    color: '##EDEDED'
