language: php

sudo: false

before_install:
  - composer config --global github-oauth.github.com $github_oauth_token

install: travis_retry composer install

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1

script:
  - vendor/bin/phpunit --coverage-clover build/coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage.clover

notifications:
  email:
    - secure: "iiseqb4k4ckQkMJnZ6Tq3YP5ilTZE4CkVgarsBpPOn+c820nP9QokGpz82D4CTGy/UB1+DfCiFH9YAFrhLP5/9Go1CHP+wYkuz9W+E8q/rm9/nBO0xutoQhOfV3MxMid69E8i4QjODq3w5mOUrmpj/8gl2FyBU1Ro1xgPSYNEQ4="
