language: php

sudo: false

before_install: composer self-update

install: composer update

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SCRUTINIZER=true
  - SCRUTINIZER=false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  exclude:
    - php: 5.4
      env: SCRUTINIZER=true
    - php: 5.5
      env: SCRUTINIZER=true
  allow_failures:
    - php: 5.6
      env: SCRUTINIZER=true

before_script:
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp tests/.env.example tests/.env

script:
  - if [ "$SCRUTINIZER" != "true" ]; then make tests ; fi;
  - if [ "$SCRUTINIZER" == "true" ]; then make travis-tests ; fi;

after_script:
  - if [ "$SCRUTINIZER" == "true" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/coverage.clover; fi;

notifications:
  email:
    - jerome@kreait.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/619e653eb8741123550e
    on_success: change
    on_failure: always
    on_start: false
