name: Emulator Tests

on:
  push:
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  emulator-tests:
    name: Emulator Tests
    runs-on: ubuntu-latest

    env:
      php-version: '8.1'
      extensions: ctype, dom, grpc, json, mbstring, openssl, xml, zip, zlib
      key: cache-emulators-7x-${{ matrix.php }}-v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v3.3.2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          tools: composer, pecl
          coverage: xdebug

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - uses: "ramsey/composer-install@v2"

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Run emulated Integration Tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          TEST_FIREBASE_APP_ID: ${{secrets.TEST_FIREBASE_APP_ID}}
          TEST_FIREBASE_RTDB_URI: ${{secrets.TEST_FIREBASE_RTDB_URI}}
          TEST_FIREBASE_TENANT_ID: ${{secrets.TEST_FIREBASE_TENANT_ID}}
          TEST_REGISTRATION_TOKENS: ${{secrets.TEST_REGISTRATION_TOKENS}}
          FIREBASE_DATABASE_EMULATOR_HOST: localhost:9100
          FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
          XDEBUG_MODE: coverage
        run: firebase emulators:exec --only auth,database --project beste-firebase 'XDEBUG_MODE=coverage vendor/bin/phpunit --group=emulator --coverage-clover=coverage.xml --log-junit=test-report.xml'

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          flags: emulator
        if: github.repository_owner == 'kreait'
